pipeline{
        agent any
        stages{
            stage('Clone Repository'){
                steps{
                    sh "git clone https://gitlab.com/qacdevops/chaperootodo_client || true"
                }
            }
            stage('Download Node.js and npm'){
                steps{
                    sh "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && sudo apt-get install -y nodejs"
                }
            }
            stage('Deploy the application'){
                steps{
                    sh "npm install && npm run serve"
                }
            }
        }
}